spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/springBoot_hw35?useUnicode=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: 'true'
    change-log: classpath:db/changelog.xml
server:
  port: '8080'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
